import { IAPIConfig } from '@/interfaces'
import {
  User,
  Permission,
  Role,
  Product,
  Review,
  Order,
  Payment,
  Medium,
  Supplier,
  Category,
  OrderProduct,
} from '@/models'

export const APIConfig: IAPIConfig = {
  resources: {
    User: {
      name: 'User',
      model: User,
      accessibleFields: [
        'id',
        'first_name',
        'last_name',
        'email',
        'phone_number',
        'country',
        'region',
        'address',
        'role_id',
        'created_at',
        'updated_at',
      ],
      requiredFields: ['id', 'role_id'],
      relations: [
        { name: 'role', model: Role },
        { name: 'reviews', model: Review },
        { name: 'orders', model: Order },
        { name: 'media', model: Medium },
        { name: 'payments', model: Payment },
      ],
    },
    Permission: {
      name: 'Permission',
      model: Permission,
      accessibleFields: ['id', 'name', 'created_at', 'updated_at'],
      requiredFields: ['id'],
      relations: [{ name: 'roles', model: Role }],
    },
    Role: {
      name: 'Role',
      model: Role,
      accessibleFields: ['id', 'name', 'created_at', 'updated_at'],
      requiredFields: ['id'],
      relations: [
        { name: 'permissions', model: Permission },
        { name: 'users', model: User },
      ],
    },
    Product: {
      name: 'Product',
      model: Product,
      accessibleFields: [
        'id',
        'title',
        'content',
        'price',
        'stock',
        'thumbnails',
        'created_at',
        'updated_at',
      ],
      requiredFields: ['id', 'supplier_id', 'category_id'],
      relations: [
        { name: 'supplier', model: Supplier },
        { name: 'reviews', model: Review },
        { name: 'category', model: Category },
      ],
    },
    Review: {
      name: 'Review',
      model: Review,
      accessibleFields: ['id', 'content', 'rate', 'created_at', 'updated_at'],
      requiredFields: ['id', 'user_id', 'product_id'],
      relations: [
        { name: 'reviewer', model: User },
        { name: 'product', model: Product },
      ],
    },
    Supplier: {
      name: 'Supplier',
      model: Supplier,
      accessibleFields: [
        'user_id',
        'name',
        'email',
        'phone_number',
        'country',
        'region',
        'address',
        'balance',
        'created_at',
        'updated_at',
      ],
      requiredFields: ['user_id'],
      relations: [
        { name: 'user', model: User },
        { name: 'products', model: Product },
      ],
    },
    Sale: {
      name: 'Sale',
      model: OrderProduct,
      accessibleFields: ['quantity'],
      requiredFields: ['order_id', 'product_id'],
      relations: [],
    },
    Order: {
      name: 'Order',
      model: Order,
      accessibleFields: ['id', 'status', 'created_at', 'updated_at'],
      requiredFields: ['id', 'user_id'],
      relations: [
        { name: 'owner', model: User },
        { name: 'products', model: Product },
      ],
    },
    Medium: {
      name: 'Medium',
      model: Medium,
      accessibleFields: [
        'id',
        'path',
        'extension',
        'type',
        'stock',
        'created_at',
        'updated_at',
      ],
      requiredFields: ['id', 'user_id'],
      relations: [{ name: 'owner', model: User }],
    },
    Payment: {
      name: 'Payment',
      model: Payment,
      accessibleFields: [
        'id',
        'method',
        'amount',
        'currency',
        'status',
        'payment_id',
        'created_at',
        'updated_at',
      ],
      requiredFields: ['id', 'user_id', 'order_id'],
      relations: [
        { name: 'payer', model: User },
        { name: 'order', model: Order },
      ],
    },
    Category: {
      name: 'Category',
      model: Category,
      accessibleFields: ['id', 'name', 'created_at', 'updated_at'],
      requiredFields: ['id', 'category_id'],
      relations: [
        { name: 'parent_category', model: Category },
        { name: 'products', model: Product },
      ],
    },
  },
}
